baseURL = "https://amitashukla.in/"
languageCode = "en-us"
title = "Amita Shukla"
theme = "gokarna"

[menu]

  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Follow"
    url = "/follow/"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6


enableGitInfo = true
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    socialIcons = [
      {name = "linkedin", url = "https://in.linkedin.com/in/shuklaamita"},
      {name = "github", url = "https://github.com/amita-shukla"},
      {name = "stackoverflow", url = "http://stackoverflow.com/users/3858467/amita"},
      {name = "goodreads", url = "https://www.goodreads.com/amita_shukla"}
    ]
    avatarURL = "/images/avatar.png"
    avatarSize = "size-m"
    description = "Software Engineer @ Cloudera"
    fontSize = "1.1rem"
    togglePreviousAndNextButtons = true
    displayReadingTime = true
    showBackToTopButton = true
    showPostsOnHomePage = "recent"
